/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistastpractico4;

/**
 *
 * @author SANTI
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdmin = new javax.swing.JMenu();
        jmiACliente = new javax.swing.JMenuItem();
        jmiBCliente = new javax.swing.JMenuItem();
        jmBusquedas = new javax.swing.JMenu();
        jmiBusCliente = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 204, 255));
        escritorio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        escritorio.setForeground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        jMenuBar1.setForeground(new java.awt.Color(153, 153, 255));

        jmAdmin.setForeground(new java.awt.Color(0, 102, 204));
        jmAdmin.setText("Administracion");
        jmAdmin.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N

        jmiACliente.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jmiACliente.setForeground(new java.awt.Color(0, 102, 204));
        jmiACliente.setText("Agregar Clientes ");
        jmiACliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAClienteActionPerformed(evt);
            }
        });
        jmAdmin.add(jmiACliente);

        jmiBCliente.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jmiBCliente.setForeground(new java.awt.Color(0, 102, 204));
        jmiBCliente.setText("Borrar Clientes");
        jmiBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBClienteActionPerformed(evt);
            }
        });
        jmAdmin.add(jmiBCliente);

        jMenuBar1.add(jmAdmin);

        jmBusquedas.setForeground(new java.awt.Color(0, 102, 204));
        jmBusquedas.setText("Busquedas");
        jmBusquedas.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N

        jmiBusCliente.setFont(new java.awt.Font("Calisto MT", 0, 12)); // NOI18N
        jmiBusCliente.setForeground(new java.awt.Color(0, 102, 204));
        jmiBusCliente.setText("Buscar Cliente");
        jmiBusCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBusClienteActionPerformed(evt);
            }
        });
        jmBusquedas.add(jmiBusCliente);

        jMenuBar1.add(jmBusquedas);

        jmSalir.setForeground(new java.awt.Color(0, 102, 204));
        jmSalir.setText("Salir");
        jmSalir.setFont(new java.awt.Font("Calisto MT", 1, 12)); // NOI18N
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarClientev ac = new AgregarClientev();
        ac.setVisible(true);
        escritorio.add(ac);
    }//GEN-LAST:event_jmiAClienteActionPerformed

    private void jmiBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBClienteActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        BorrarClienteVista bc = new BorrarClienteVista();
        bc.setVisible(true);
        escritorio.add(bc);
    }//GEN-LAST:event_jmiBClienteActionPerformed

    private void jmiBusClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBusClienteActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        BuscarClienteVista buscarc = new BuscarClienteVista();
        buscarc.setVisible(true);
        escritorio.add(buscarc);
    }//GEN-LAST:event_jmiBusClienteActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jmSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdmin;
    private javax.swing.JMenu jmBusquedas;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiACliente;
    private javax.swing.JMenuItem jmiBCliente;
    private javax.swing.JMenuItem jmiBusCliente;
    // End of variables declaration//GEN-END:variables
}
